swagger: '2.0'
info:
  description: Sample swagger for Report microservices
  version: Version - 1.0
  title: Outreach
  termsOfService: Project Url
  contact:
    name: Santhosh and Aravinthan P
  license:
    name: Api License
host: 'localhost:8091'
basePath: /
tags:
  - name: report-controller
    description: Report Controller
paths:
  /report:
    post:
      tags:
        - report-controller
      summary: To filter the report
      description: Put the report filter in the body
      operationId: reportFilterUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: report
          description: Give the report filter details
          required: true
          schema:
            $ref: '#/definitions/Report'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
             $ref: '#/definitions/Report'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false

    get:
      tags:
        - report-controller
      summary: Provide all the event report
      description: All the event reports are fetched
      operationId: getAllEventReportsUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Report'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  Report:
    type: object
    properties:
      event:
        $ref: '#/definitions/Event'
      rating:
        type: string
    title: Report
  Employee:
    type: object
    properties:
      email:
        type: string
      firstName:
        type: string
      id:
        type: integer
        format: int32
      lastName:
        type: string
    title: Employee
  Event:
    type: object
    properties:
      base_location:
        type: string
      event_date:
        type: string
        format: date-time
      event_id:
        type: integer
        format: int32
      event_name:
        type: string
      event_status:
        type: string
      total_travel_hour:
        type: integer
        format: int32
      total_volunteer_hour:
        type: integer
        format: int32
      total_volunteers:
        type: integer
        format: int32
      venue_address:
        type: string
    title: Event
  